trigger:
- main  

pool:
  name: 'Default'  # Nome do seu pool auto-hospedado

steps:
# Fazer o checkout do código do GitHub (usando a conexão vinculada)
- checkout: self  # Checkout automático do repositório vinculado

# Instalar o Docker (se necessário)
- task: DockerInstaller@0
  inputs:
    dockerVersion: '27.2.1'

# Instalar o Docker Compose
- script: |
    # Definir o diretório de instalação
    INSTALL_DIR=$(mktemp -d)
    DOCKER_COMPOSE_VERSION=1.29.2
    curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ${INSTALL_DIR}/docker-compose
    chmod +x ${INSTALL_DIR}/docker-compose
    # Adicionar o diretório ao PATH
    export PATH=$PATH:${INSTALL_DIR}
  displayName: 'Instalar Docker Compose'

# Executar Docker Compose
- script: |
    docker-compose -f $(Build.SourcesDirectory)/docker-compose.yml up -d
  displayName: 'Executar Docker Compose'
